### ISSUE TITLE
The first community call resurrection 

### ISSUE THREAD

**Issue by tonyfast** [isabela-pf/jupyter-communitycalls#1]
11/17/2020

- [x] add it to personal and organizational calendars
- [x] [hackmd agenda and notes](https://hackmd.io/grCMoA5VTrqcaDSwOPJJnw)
- [x] announce the event
  - [x] social media (gonzalo has access to pj twitter)
  - [x] post on discourse
- [x] talk submission
  - [x] issue template submission
  - [x] google form per event
- [x] upload video to youtube

**Comment by isabela-pf** [comment]
- [ ] upload meeting minutes to documentation

- [ ] add youtube and agenda/notes link to discourse page
