### ISSUE TITLE
Link external resources

### ISSUE THREAD

**Issue by isabela-pf** [isabela-pf/jupyter-communitycalls#2]
- [x] [Jupyter Code of Conduct](https://jupyter.org/conduct)
- [x] [Request to present form](https://docs.google.com/forms/d/e/1FAIpQLSexMC-hiXhw18yyaLajobk7geqz6SoMjBwtc9Y0GsCzMiugxw/viewform?usp=sf_link)
- [x] [Feedback form](https://docs.google.com/forms/d/e/1FAIpQLScwfYswVhafS9PVIoQYepIExq3f-FP7EmsAFULCiTIgc7mRSA/viewform?usp=sf_link)
- [x] [Graphics in slides](https://docs.google.com/presentation/d/1qaDtW_EluCBI9EFUueFDjLGoG3XxfzqbfFdAKmKPEwo/edit?usp=sharing)
- [x] Intro and outro slides (for hosts)
- [x] [Jupyter community calendar](https://jupyter.readthedocs.io/en/latest/community/content-community.html#jupyter-community-meetings)
- [x] [Jupyter community call minutes](https://jupyter.readthedocs.io/en/latest/community/community-call-notes/index.html)
- [x] [Recorded calls playlist](https://www.youtube.com/playlist?list=PLUrHeD2K9Cmkoamm4NjLmvXC4Y6E1o8SP)

**Comment by tonyfast** [comment]
* move the requests to present form to the top.

**Comment by isabela-pf** [comment]
Closed by 15e6b17
