### ISSUE TITLE
Planning guide/to-do templates

### ISSUE THREAD

**Issue by isabela-pf** [isabela-pf/jupyter-communitycalls#3]
Make a template so it's easy to have a ready-to-go to do list to start each call with. No more starting from scratch! 🌻 

- [x] .md file
- [x] issue template

**Comment by tonyfast** [comment]
i look forward to your feelings after the first commnity call.

**Comment by isabela-pf** [comment]
For reference, I use [this tutorial](https://medium.com/better-programming/github-templates-the-smarter-way-to-formalize-pull-requests-among-development-teams-89f8d6a204f) to make a PR template.

Closed by 1c7ca7f.
